# Generated by Django 3.0.3 on 2020-02-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="slug", field=models.SlugField(max_length=6),
        ),
        migrations.AlterField(
            model_name="usercart",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
