# Generated by Django 2.2.5 on 2019-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190925_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Salad'), ('SU', 'Subs'), ('SP', 'Sicilian Pizza'), ('RP', 'Regular Pizza'), ('DP', 'Dinner Plate'), ('P', 'Pasta')], max_length=2),
        ),
    ]
