# Generated by Django 2.2.5 on 2019-10-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191005_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='addon',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addon1',
            field=models.CharField(blank=True, choices=[('Peperoni', 'Peperoni'), ('None', 'None'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Zucchini', 'Zucchini'), ('Ham', 'Ham'), ('Fresh Garlic', 'Fresh Garlic'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addon2',
            field=models.CharField(blank=True, choices=[('Peperoni', 'Peperoni'), ('None', 'None'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Zucchini', 'Zucchini'), ('Ham', 'Ham'), ('Fresh Garlic', 'Fresh Garlic'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addon3',
            field=models.CharField(blank=True, choices=[('Peperoni', 'Peperoni'), ('None', 'None'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Zucchini', 'Zucchini'), ('Ham', 'Ham'), ('Fresh Garlic', 'Fresh Garlic'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives')], max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
    ]
